### PR TITLE
add draft of first team blog post

### PR DESCRIPTION
**Pull request by alicetragedy**
this post would be ready to go, we just have to reach a consensus on the slug conventions (eg. without date?) and double-check the categories, but that's all.

### CODE REVIEW

**Comment by alicetragedy** [comment]
@DoubleMalt I added the second blog post in this PR. could you or @kermit666 take care of the merging and publishing/building while I'm away? Changed the dates already to next week and week after next, feel free to adapt as needed. thanks! :sunny:

**Comment by metakermit** [comment]
This looks good to me (sorry for not reviewing sooner, was quite busy with development tasks).

**Comment by DoubleMalt** [comment]
Yes, looks, good. Caroline offered to proofread it, so I will run it by her
as a native speaker.

**Comment by alicetragedy** [comment]
@kermit666 totally understandable, no problem. What's the status on the blog? Shall I adapt the dates as needed?
@DoubleMalt that's a good idea. I actually only did a bit of an intro and left most of the answers as they were since that seemed easiest (and also, a better format than a huge block of text).

**Comment by metakermit** [comment]
Maybe this weekend? It's ok, you don't have to worry about dates in the files. I can set that up when I'm merging.

**Comment by alicetragedy** [comment]
:+1:

**Comment by m8p** [comment]
Hi,
I don't know who has set up this mail multiplying list, but it makes definitely no sense to discuss topics in that way and fill two email accounts from me: navigator@cloudfleet.io is the apropriate Adresse but PLEASE it is not useful to chat bilaterally in minutes rhythm on such a channel - there was an different media. .. was it called chat or in earlier times Bulletin board?

CU
N

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Dražen Lučanin notifications@github.com
Datum: 2015.09.08 15:56 (GMT+01:00)
An: cloudfleet/blog blog@noreply.github.com
Betreff: Re: [blog] add draft of first team blog post (#1)

Maybe this weekend? It's ok, you don't have to worry about dates in the files. I can set that up when I'm merging.

**Comment by alicetragedy** [comment]
@m8p this is a normal pull-request-related conversation. 
It's not a mailing list, meaning no one has set it up to mail updates to everyone – they are being sent automatically because you are part of the Cloudfleet organisation on GitHub. You have to turn off your own GitHub notifications from the platform to stop the notifications, as we can't do it for you, I don't think.

**Comment by m8p** [comment]
...the mail is always sent to martin@povazay.com and navigator@cloudfleet.io.
The latter email address is ok, sending a copy to the first is redundant and since I do not know who entered the non - cloudfleet mail into the 'distributor' , I  requested the update.
The 'flood' looked like the result from an mailing list. ...

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Laura notifications@github.com
Datum: 2015.09.08 16:45 (GMT+01:00)
An: cloudfleet/blog blog@noreply.github.com
Cc: Martin Povazay martin@povazay.com
Betreff: Re: [blog] add draft of first team blog post (#1)

@m8phttps://github.com/m8p this is a normal pull-request-related conversation.
It's not a mailing list, meaning no one has set it up to mail updates to everyone – they are being sent automatically because you are part of the Cloudfleet organisation on GitHub. You have to turn off your own GitHub notifications from the platform to stop the notifications, as we can't do it for you, I don't think.

**Pull request merged**
